#!/bin/bash
CHK=$(rpm -qa |grep -i pyyaml)
if [ -z "$CHK" ]; then
        echo "Please, install PyYAML"
        exit 1
fi

python -c 'import yaml,sys;yaml.safe_load(sys.stdin)' < $1 2> /dev/null
if [ $? -ne 0 ]; then
        echo "YAML syntax failed"
        exit 1
fi
echo "YAML syntax success"
